module.controller('ScoreCtrl',['$scope','$http','$state','ObjectFactory','$stateParams',function($scope,$http,$state,ObjectFactory,$stateParams){
    $scope.init=function(){
        $scope.md5=$stateParams.md5;
        $scope.scores=ObjectFactory.get('scores');
        if(!$scope.scores){
            $http.post($scope.baseUrl+'?m=Home&c=Index&a=score',{}).success(function($data){
                $scope.scores=$data;
                ObjectFactory.set('scores',$scope.scores);
            });
        }
    };
}])